/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { BuntinglabsApi } from "@fern-api/buntinglabs";
import * as core from "../../../../core";

export const GeocodeSectionResponse: core.serialization.ObjectSchema<
    serializers.GeocodeSectionResponse.Raw,
    BuntinglabsApi.GeocodeSectionResponse
> = core.serialization.object({
    type: core.serialization.string(),
    properties: core.serialization.lazyObject(async () => (await import("../../..")).GeoCodeSectionProperties),
    geometry: core.serialization.lazyObject(async () => (await import("../../..")).FeatureGeometry),
});

export declare namespace GeocodeSectionResponse {
    interface Raw {
        type: string;
        properties: serializers.GeoCodeSectionProperties.Raw;
        geometry: serializers.FeatureGeometry.Raw;
    }
}
