/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CountFeaturesRequest {
    /**
     * This is a list of tags in the form `key=value` to filter features for. All features extracted will satisfy each of the passed tags given by this parameter.
     * This tag list can be created by forming an array of `key=value` items and joining them into one string with the `&` character.
     * Because both = and & are reserved characters in URIs, this list must be URL encoded.
     * An example list of tags could be `leisure=park` and `name=Westglen Park`. This matches parks that have the name Westglen Park. To set this parameter, we’ll URL encode leisure=park&name=Westglen Park.
     * Documentation on tags can be found on the [TagInfo](https://docs.buntinglabs.com/openstreetmap-api/count#:~:text=found%20on%20the-,TagInfo,-resource%20website) resource website.
     *
     */
    tags: string;
    /**
     * This is the bounding box for extracted features. The coordinates (in EPSG:4326) of the bounding box are required to be in (minimum longitude, minimum latitude, maximum longitude, maximum latitude) order.
     * Coordinates are expressed as signed floats joined by commas.
     * An example bounding box in the US could be `-108.984375,32.026706,-103.051758,37.195331`.
     * You can create a bounding box `on bboxfinder`, or in shapely by invoking the `bounds` property on a geometry.
     *
     */
    bbox?: string;
    /**
     * Your account's API key.
     * You can create an API key by registering for an account and copy and paste it from your account dashboard.
     *
     */
    apiKey: string;
}
