/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IncomeResponse {
    /** The median income of the population of the circle, according to US Census data. */
    medianIncome?: number;
    /** A descriptive source for the data, including the year the data was collected. */
    source?: string;
}
