/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PopulationResponse {
    /** The expected number of residents in the circle, based on US census data. */
    population?: number;
    /** A descriptive source for the data, including the year the data was collected. */
    source?: string;
}
