/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { BuntinglabsApi } from "@fern-api/buntinglabs";
import * as core from "../../../../core";

export const CountFeatureResponse: core.serialization.ObjectSchema<
    serializers.CountFeatureResponse.Raw,
    BuntinglabsApi.CountFeatureResponse
> = core.serialization.object({
    featureCount: core.serialization.property("feature_count", core.serialization.number()),
});

export declare namespace CountFeatureResponse {
    interface Raw {
        feature_count: number;
    }
}
