/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PoiRequest {
    /**
     * The location of the area to describe.
     */
    location: string;
    /**
     * Your account's API key. You can create an API key by [registering for an account](https://buntinglabs.com/account/register) and copy and paste it from your [account dashboard](https://buntinglabs.com/dashboard).
     */
    apiKey: string;
}
