/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GeocodeSectionRequest {
    /**
     * The section number, between 1 and 36 (inclusive), specifies which section of the township should be returned.
     */
    section: number;
    /**
     * The range specifies the numbered distance and bearing (east or west) from the principal meridian.
     */
    range: string;
    /**
     * The township specifies the numbered distance and bearing (north or south) from the baseline associated with each principal meridian.
     */
    township: string;
    /**
     * This can take any value below. The values are provided alongside their approximate count, based on the total area surveyed to that meridian.
     */
    meridian: string;
    /**
     * Your account's API key. You can create an API key by [registering for an account](https://buntinglabs.com/account/register) and copy and paste it from your [account dashboard](https://buntinglabs.com/dashboard).
     */
    apiKey: string;
}
