/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CountFeatureResponse {
    /** The number of features matching the filter tags and bounding box */
    featureCount?: number;
}
