/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { BuntinglabsApi } from "@fern-api/buntinglabs";

export interface Feature {
    type: string;
    geometry: BuntinglabsApi.FeatureGeometry;
    properties?: BuntinglabsApi.FeatureProperties;
}
