/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { BuntinglabsApi } from "@fern-api/buntinglabs";

export interface FeatureGeometry {
    type: string;
    coordinates: BuntinglabsApi.Coordinate[][];
}
