/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { BuntinglabsApi } from "@fern-api/buntinglabs";

export interface FeatureCollection {
    type: string;
    features: BuntinglabsApi.Feature[];
}
