/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const BuntinglabsApiEnvironment = {
    Production: "https://osm.buntinglabs.com/v1/",
} as const;

export type BuntinglabsApiEnvironment = typeof BuntinglabsApiEnvironment.Production;
