/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { BuntinglabsApi } from "@fern-api/buntinglabs";
import * as core from "../../../../core";

export const Coordinate: core.serialization.Schema<serializers.Coordinate.Raw, BuntinglabsApi.Coordinate> =
    core.serialization.number();

export declare namespace Coordinate {
    type Raw = number;
}
