/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { BuntinglabsApi } from "@fern-api/buntinglabs";
import * as core from "../../../../core";

export const FeatureProperties: core.serialization.Schema<
    serializers.FeatureProperties.Raw,
    BuntinglabsApi.FeatureProperties
> = core.serialization.unknown();

export declare namespace FeatureProperties {
    type Raw = unknown;
}
