/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { BuntinglabsApi } from "@fern-api/buntinglabs";
import * as core from "../../../../core";

export const FeatureGeometry: core.serialization.ObjectSchema<
    serializers.FeatureGeometry.Raw,
    BuntinglabsApi.FeatureGeometry
> = core.serialization.object({
    type: core.serialization.string(),
    coordinates: core.serialization.list(
        core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).Coordinate))
    ),
});

export declare namespace FeatureGeometry {
    interface Raw {
        type: string;
        coordinates: serializers.Coordinate.Raw[][];
    }
}
