/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { BuntinglabsApi } from "@fern-api/buntinglabs";
import * as core from "../../../../core";

export const GeocodeGeomtery: core.serialization.ObjectSchema<
    serializers.GeocodeGeomtery.Raw,
    BuntinglabsApi.GeocodeGeomtery
> = core.serialization.object({
    type: core.serialization.string(),
    coordinates: core.serialization.string(),
});

export declare namespace GeocodeGeomtery {
    interface Raw {
        type: string;
        coordinates: string;
    }
}
