/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { BuntinglabsApi } from "@fern-api/buntinglabs";

export interface GeocodeSectionResponse {
    type: string;
    properties: BuntinglabsApi.GeoCodeSectionProperties;
    geometry: BuntinglabsApi.FeatureGeometry;
}
